server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  datasource:
    url: ${DATABASE_URL}?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false

openai:
  model: gpt-4
  api:
    url: https://api.openai.com/v1/chat/completions
    key: ${OPEN_API_KEY}
logging:
  level:
    '[com.example.kakao]': INFO
    '[org.hibernate.type]': TRACE
